-- Textes de remise et d attente en francais releves sur Wowhead FR (04/10/2026).
-- Retenus seulement si l anglais de Wowhead concorde avec le notre (ressemblance >= 0,97)
-- et si la page francaise est vraiment traduite. INSERT IGNORE : ne remplace rien.
SET NAMES utf8mb4;
INSERT IGNORE INTO quest_offer_reward_locale (ID, locale, RewardText, VerifiedBuild) VALUES (16, 'frFR', 'Merci, $n ! Et revenez si vous voulez refaire affaire.', 0);
INSERT IGNORE INTO quest_offer_reward_locale (ID, locale, RewardText, VerifiedBuild) VALUES (172, 'frFR', 'Zig zig ! Moi je m\'appelle Grunth. C\'est vous qui vous occupez de moi ? Vous êtes un aventurier, comme mon papa et ma maman avant. La gouvernante m\'a dit qu\'ils sont morts en se battant avec plein d\'honneur. C\'est chouette de vous rencontrer.$B$BJ\'espère qu\'on va bien s\'amuser tous les deux. Y a plein de choses que j\'aimerais bien faire, et la gouvernante elle m\'a dit que vous allez être comme mon grand frère cette semaine. Ça va être génial !', 0);
INSERT IGNORE INTO quest_offer_reward_locale (ID, locale, RewardText, VerifiedBuild) VALUES (182, 'frFR', 'Espérons que cela suffira. Courbenclume n’a plus rien à craindre des Trolls pour un certain temps. Maintenant, tâchons de découvrir ce qui les agite autant.', 0);
INSERT IGNORE INTO quest_offer_reward_locale (ID, locale, RewardText, VerifiedBuild) VALUES (208, 'frFR', 'Sacrément bien joué ! Hourra ! Félicitations, $n ! Vous avez réussi là où tant d\'autres ont échoué.$B$BC\'est pour moi un grand honneur de vous compter parmi mes camarades. Personne ne peut remettre en doute votre talent dans l\'art de la chasse et de la traque !$B$BBravo à vous ! Bravo !', 0);
INSERT IGNORE INTO quest_offer_reward_locale (ID, locale, RewardText, VerifiedBuild) VALUES (218, 'frFR', 'Je suis content que vous soyez de retour en un seul morceau, $n. On ne le dirait peut-être pas, mais vous venez de jouer un rôle crucial dans la protection de Courbenclume.$B$BTenez, acceptez ceci en gage de ma gratitude.', 0);
INSERT IGNORE INTO quest_offer_reward_locale (ID, locale, RewardText, VerifiedBuild) VALUES (309, 'frFR', 'Vous m\'apportez des nouvelles inquiétantes. Imaginer que les Sombrefer ont des sympathisants capables de leur procurer ce type de matériel pour mener leurs plans à bien...$B$BCe problème devra être réglé, mais ni par moi, ni maintenant. Merci d\'avoir protégé Huldar et le chariot !', 0);
INSERT IGNORE INTO quest_offer_reward_locale (ID, locale, RewardText, VerifiedBuild) VALUES (313, 'frFR', 'Merci de votre aide, $n. Ces derniers temps, nos forces sont déployées en troupes de quelques unités, et trois montagnards de plus pourraient faire la différence entre victoire et défaite à Kharanos.', 0);
INSERT IGNORE INTO quest_offer_reward_locale (ID, locale, RewardText, VerifiedBuild) VALUES (412, 'frFR', 'Ces engrenages gyromécaniques sont en parfait état ! Les deux pilotes de chars que voici vont bientôt pouvoir repartir au front !', 0);
INSERT IGNORE INTO quest_offer_reward_locale (ID, locale, RewardText, VerifiedBuild) VALUES (433, 'frFR', 'Quel soulagement ! Je suis content de voir que vous avez pu sauver autant de mineurs, $n. Je vais m’assurer que leurs familles soient prévenues immédiatement.$B$BJe dirai au sénat avec quelle bravoure vous nous avez aidés à reconquérir les mines.', 0);
INSERT IGNORE INTO quest_offer_reward_locale (ID, locale, RewardText, VerifiedBuild) VALUES (476, 'frFR', 'Par les étoiles ! C’est vraiment troublant !$B$BLa corruption des Furbolgs nous a déjà posé problème par le passé, mais elle aurait dû disparaître avec la purification de Teldrassil. Je crains pour la sécurité de toute notre race si les bénédictions des aspects eux-mêmes sont incapables de sauver notre grand arbre.', 0);
INSERT IGNORE INTO quest_offer_reward_locale (ID, locale, RewardText, VerifiedBuild) VALUES (485, 'frFR', 'Vous placez l\'œuf... la balise de détresse... dans le poulet... le robot guidé.$B$BVous entendez des bourdonnements venant de l\'intérieur du robot quand il essaye de se relever. Après l\'activation du robot, la voix d\'Orguignard retentit de nouveau, mais maintenant elle vient de l\'intérieur du robot :$B$B« OOX-09/HL fonctionne, mais il a besoin de grosses réparations ! Il est trop lourd pour vous... Mais je pense que j\'ai une idée. Voudriez-vous bien le surveiller encore un peu ? »', 0);
INSERT IGNORE INTO quest_offer_reward_locale (ID, locale, RewardText, VerifiedBuild) VALUES (486, 'frFR', '$n, vous avez prouvé que vous étiez un $c de très grande valeur. Un $r qui suit le chemin de l’honneur comme vous le faites est assuré de rencontrer la gloire dans ce monde.$B$BGrâce à la mort d’Ursal, nos druides autrefois endormis sont en sécurité, mais la source de sa corruption hante toujours nos forêts. Avec le temps, j’espère que vous trouverez ce mal et que vous le détruirez pour le bien de tous nos semblables. Vous êtes promis à de hautes destinées, jeune $c.', 0);
INSERT IGNORE INTO quest_offer_reward_locale (ID, locale, RewardText, VerifiedBuild) VALUES (487, 'frFR', 'Vous avez bien servi le bon peuple de Dolanaar et de Darnassus, brave $c. En tant que membre des Sentinelles de Teldrassil, je salue vos efforts.', 0);
INSERT IGNORE INTO quest_request_items_locale (ID, locale, CompletionText, VerifiedBuild) VALUES (84, 'frFR', 'Ugh... Je suis affamé ! Vous m\'avez apporté la tourte, $n ?', 0);
INSERT IGNORE INTO quest_request_items_locale (ID, locale, CompletionText, VerifiedBuild) VALUES (171, 'frFR', 'C\'est un plaisir de vous revoir, $n. Avez-vous pu accomplir les tâches pour lesquelles vous vous êtes porté volontaire pendant la Semaine des enfants ?', 0);
INSERT IGNORE INTO quest_request_items_locale (ID, locale, CompletionText, VerifiedBuild) VALUES (188, 'frFR', 'Comment se passe la chasse ?', 0);
INSERT IGNORE INTO quest_request_items_locale (ID, locale, CompletionText, VerifiedBuild) VALUES (193, 'frFR', 'Vous êtes toujours en vie ? Excellent ! Alors, comment se déroule la chasse ?', 0);
INSERT IGNORE INTO quest_request_items_locale (ID, locale, CompletionText, VerifiedBuild) VALUES (197, 'frFR', 'Alors, comme ça, vous traquez Téthis ? Vous avez rabattu votre proie jusqu\'au camp, c\'est ça ?', 0);
INSERT IGNORE INTO quest_request_items_locale (ID, locale, CompletionText, VerifiedBuild) VALUES (218, 'frFR', '$n ! Alors ?', 0);
INSERT IGNORE INTO quest_request_items_locale (ID, locale, CompletionText, VerifiedBuild) VALUES (384, 'frFR', 'Il me faudrait ces côtes de sanglier des rochers et une chope de bière au malt Rhapsody, $n.', 0);
INSERT IGNORE INTO quest_request_items_locale (ID, locale, CompletionText, VerifiedBuild) VALUES (412, 'frFR', 'Ces pilotes sont impatients de retrouver leur char à vapeur et de repartir au front. Ne les faisons pas attendre.', 0);
INSERT IGNORE INTO quest_request_items_locale (ID, locale, CompletionText, VerifiedBuild) VALUES (485, 'frFR', 'Vous découvrez l\'épave d\'une sorte de... robot poulet ? La voix émerge de l\'œuf une nouvelle fois :$B$B« Oui, excellent travail ! C\'est bien mon robot guidé, mes détecteurs m\'indiquent qu\'il doit être relancé avant de pouvoir revenir à Baie-du-Butin pour y être réparé. Allez-y et placez la balise dans la machine. La balise s\'occupera du reste ! »', 0);
